# Trigger the pipeline when changes occur in the 'vote' directory
trigger:
  paths:
    include:
      - vote/*

# Resources: Use the current repository as the source
resources:
  - repo: self

# Define pipeline variables
variables:
  # Service connection for Docker registry (configured during pipeline creation)
  dockerRegistryServiceConnection: '6d98ab55-5471-477e-b47c-a3c92999a578'

  # Docker image repository name in Azure Container Registry
  imageRepository: 'votingapp'

  # Azure Container Registry URL
  containerRegistry: 'hrithiknaikcicd.azurecr.io'

  # Path to Dockerfile for building the image
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'

  # Tag to use for the Docker image, based on the Build ID
  tag: '$(Build.BuildId)'

# Define the agent pool
pool:
  name: 'azureagent'

# Stages: Define the steps to build, push, and update the Kubernetes manifests
stages:
  
  # Stage 1: Build the Docker image
  - stage: Build
    displayName: 'Build Docker Image'
    jobs:
      - job: Build
        displayName: 'Build Docker Image'
        steps:
          - task: Docker@2
            displayName: 'Build Image'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)'
              command: 'build'
              Dockerfile: '$(dockerfilePath)'  # Use the variable here
              tags: '$(tag)'

  # Stage 2: Push the Docker image to Azure Container Registry
  - stage: Push
    displayName: 'Push Docker Image'
    jobs:
      - job: Push
        displayName: 'Push Docker Image'
        steps:
          - task: Docker@2
            displayName: 'Push Image'
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)'
              command: 'push'
              tags: '$(tag)'

  # Stage 3: Update Kubernetes manifests with the new image tag
  - stage: Update
    displayName: 'Update Kubernetes Manifests'
    jobs:
      - job: Update
        displayName: 'Update Kubernetes Manifests'
        steps:
          - task: ShellScript@2
            displayName: 'Update Kubernetes Manifests'
            inputs:
              scriptPath: 'scripts/updateK8sManifests.sh'
              args: 'vote $(imageRepository) $(tag)'  # Pass the image repository and tag to the script
